# Generated by Django 4.2.16 on 2025-04-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "building_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("building_title", models.CharField(max_length=200)),
                ("building_description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BuildingAssign",
            fields=[
                (
                    "building_assign_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("building_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inprogress", "In Progress"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="time_management.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "calendar_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("month_name", models.CharField(max_length=20)),
                ("day", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("day_name", models.CharField(max_length=20)),
                ("week_of_year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_holiday", models.BooleanField(default=False)),
                ("fiscal_year", models.IntegerField()),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "employee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fathers_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=40, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("doj", models.DateField(blank=True, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "personal_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "aadhaar_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("PAN", models.CharField(blank=True, max_length=10, null=True)),
                ("UAN", models.CharField(blank=True, max_length=12, null=True)),
                ("pf_number", models.CharField(blank=True, max_length=20, null=True)),
                ("esi_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("passport_validity", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("resigned", "Resigned"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("permanent_address", models.TextField(blank=True, null=True)),
                ("local_address", models.TextField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "year_of_passing",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "previous_company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "arris_experience",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "total_experience",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "experience_in_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "probation_confirmation_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "employee_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "reporting_manager",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("relieving_date", models.DateField(blank=True, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=11, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("blood_group", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.CharField(
                        blank=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("project_title", models.CharField(max_length=255)),
                ("project_type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("project_description", models.TextField(blank=True, null=True)),
                ("area_of_work", models.CharField(max_length=255)),
                ("project_code", models.CharField(max_length=100, unique=True)),
                ("subdivision", models.CharField(max_length=100)),
                ("discipline_code", models.CharField(max_length=100)),
                ("discipline", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.BooleanField(blank=True, default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("task_title", models.CharField(max_length=200)),
                ("task_description", models.TextField(blank=True, null=True)),
                ("priority", models.CharField(max_length=50)),
                (
                    "attachments",
                    models.FileField(
                        blank=True, null=True, upload_to="tasks/attachments/"
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("hr", "HR"),
                            ("teamlead", "Team Lead"),
                            ("employee", "Employee"),
                            ("manager", "Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssign",
            fields=[
                (
                    "task_assign_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("task_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inprogress", "In Progress"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "building_assign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="time_management.buildingassign",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="time_management.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAssign",
            fields=[
                (
                    "project_assign_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("project_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inprogress", "In Progress"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="time_management.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeavesTaken",
            fields=[
                (
                    "leave_taken_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("leave_type", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration", models.IntegerField()),
                ("reason", models.TextField()),
                ("resumption_date", models.DateField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_attachments/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="time_management.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeavesAvailable",
            fields=[
                (
                    "leave_avail_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("sick_leave", models.IntegerField(default=0)),
                ("casual_leave", models.IntegerField(default=0)),
                ("comp_off", models.IntegerField(default=0)),
                ("earned_leave", models.IntegerField(default=0)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hierarchy",
            fields=[
                (
                    "hierarchy_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
                (
                    "reporting_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buildingassign",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="time_management.employee",
            ),
        ),
        migrations.AddField(
            model_name="buildingassign",
            name="project_assign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.projectassign",
            ),
        ),
        migrations.CreateModel(
            name="BiometricData",
            fields=[
                (
                    "biometric_id",
                    models.CharField(
                        blank=True, max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("employee_code", models.CharField(max_length=50)),
                ("employee_name", models.CharField(max_length=100)),
                ("shift", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("in_time", models.TimeField()),
                ("out_time", models.TimeField()),
                ("work_duration", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ot",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="OT"
                    ),
                ),
                ("total_duration", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_management.employee",
                    ),
                ),
            ],
        ),
    ]
