# Generated by Django 4.2.16 on 2025-03-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingassign",
            name="building",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.building",
            ),
        ),
        migrations.AlterField(
            model_name="buildingassign",
            name="project_assign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.projectassign",
            ),
        ),
        migrations.AlterField(
            model_name="projectassign",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.project",
            ),
        ),
        migrations.AlterField(
            model_name="taskassign",
            name="building_assign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.buildingassign",
            ),
        ),
        migrations.AlterField(
            model_name="taskassign",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="time_management.task",
            ),
        ),
    ]
