from django.contrib import admin

from .models import (
    User,
    Employee,
    SalaryBreakdown,
    Modifications,
    Designation,
    Assets,
    Dependant,
    Education,
    WorkExperience,
    LanguagesKnown,
    Hierarchy,
    LeavesAvailable,
    LeavesTaken,
    Calendar,
    BiometricData,
    AreaOfWork,
    Discipline,
    Project,
    Building,
    Task,
    ProjectAssign,
    BuildingAssign,
    TaskAssign,
    TimeSheet,
    Attachment,
    EmployeeAttachment,
    CompanyPolicy,
    CompOff,
    Variation,
    CompOffRequest,
    CompOffExpiry,
    Client,
    ClientPOC,
    Department,
    LeaveOpeningBalance,
    MonthlyLeaveAvailed,
    MonthlyLeaveBalance,
    LeaveDay,
)

admin.site.register(Employee)

admin.site.register(User)
admin.site.register(Hierarchy)

admin.site.register(LeavesAvailable)
admin.site.register(LeavesTaken)
admin.site.register(Calendar)
admin.site.register(BiometricData)
admin.site.register(Project)
admin.site.register(AreaOfWork)
admin.site.register(Discipline)
admin.site.register(Building)
admin.site.register(Task)
admin.site.register(ProjectAssign)
admin.site.register(BuildingAssign)
admin.site.register(TaskAssign)
admin.site.register(TimeSheet)
admin.site.register(Attachment)
admin.site.register(CompOff)
admin.site.register(CompOffRequest)
admin.site.register(CompOffExpiry)
admin.site.register(Variation)
admin.site.register(Modifications)
admin.site.register(Designation)
admin.site.register(Department)
admin.site.register(Assets)
admin.site.register(Dependant)
admin.site.register(Education)
admin.site.register(WorkExperience)
admin.site.register(LanguagesKnown)
admin.site.register(EmployeeAttachment)
admin.site.register(CompanyPolicy)
admin.site.register(SalaryBreakdown)
admin.site.register(ClientPOC)
admin.site.register(Client)
admin.site.register(LeaveOpeningBalance)
admin.site.register(MonthlyLeaveAvailed)
admin.site.register(MonthlyLeaveBalance)
admin.site.register(LeaveDay)
